def MAP_CASTLE equ $00
def MAP_VILLAGE equ $01
def MAP_BAZAAR equ $02
def MAP_TRVGATE equ $03
def MAP_FARM equ $04
def MAP_SHPRD equ $05
def MAP_BATTLE1 equ $06
def MAP_BATTLE2 equ $07
def MAP_NEST equ $08
def MAP_STRDNGN equ $09
def MAP_WTMEDAL equ $0a ;king's secret path
;def unnamed equ $0b ;Castle treasure room
def MAP_EGCNSLT equ $0c ;egg consultant
def MAP_PRDPRNT equ $0d
;def unnamed equ $0e ; Castle treasure room
def MAP_CHKSTND equ $0f ;bank
def MAP_CUTYGRL equ $10
;def unnamed equ $11
def MAP_LIBRARY equ $12
def MAP_STACK equ $13 ;Library back room
;def unnamed equ $14
;def unnamed equ $15
def MAP_MEDALMA equ $16
;def unnamed equ $17 ;corrupted version of copycat's room
def MAP_IN_WELL equ $18
def MAP_MDYHAND equ $19
def MAP_SPONSER equ $1a
def MAP_STABLEL equ $1b ;kingslime
def MAP_STABLER equ $1c ;coffin room
def MAP_SCHOOL equ $1d
def MAP_BAR equ $1e
def MAP_QUEEEN equ $1f
;def unnamed equ $20
;def unnamed equ $21
;def unnamed equ $22
def MAP_CHMBROP equ $23 ;first gate room
def MAP_CHMBR_G equ $24
def MAP_CHMBR_F equ $25
def MAP_CHMBR_E equ $26
def MAP_CHMBR_D equ $27
def MAP_CHMBR_C equ $28
def MAP_CHMBR_B equ $29
def MAP_CHMBR_A equ $2a
def MAP_CHMBR_S equ $2b
def MAP_CHMBR_1 equ $2c
def MAP_CHMBR_2 equ $2d
def MAP_CHMBR_3 equ $2e
def MAP_TERRYS equ $2f
def MAP_OLDWELL equ $30 ;Hale's boss room
def MAP_S_CAVE equ $31 ;heavy princess's room
def MAP_MELKID equ $32 ;Golm's boss room
def MAP_NEST_2 equ $33 ;Just named NEST. MadCat's boss room.
def MAP_ILMWOOD equ $34
def MAP_TOMDOLA equ $35
def MAP_CASINO equ $36
def MAP_GODTWR equ $37
def MAP_LONDARG equ $38
def MAP_RENUL equ $39
def MAP_ARPTWR equ $3a
def MAP_DANCER equ $3b
def MAP_T_CAVE equ $3c
def MAP_SPRING equ $3d
def MAP_HAPPY equ $3e
def MAP_LIFECOD equ $3f
def MAP_TRIAL1 equ $40
def MAP_TRIAL2 equ $41
def MAP_M_CAVE equ $42
def MAP_PRISON equ $43
def MAP_Z_CAVE equ $44
def MAP_HELCLD equ $45
def MAP_DRGCSTL equ $46
def MAP_HRGNCSL equ $47
def MAP_BRMSCSL equ $48
def MAP_ZOMACSL equ $49
def MAP_MT_TOP equ $4a
def MAP_ATTOM equ $4b
def MAP_EVIL_MT equ $4c
def MAP_MUDOCSL equ $4d
def MAP_BTWECSL equ $4e
def MAP_SCRTMAP equ $4f
def MAP_ITEMSP equ $50
def MAP_CHURCH equ $51
def MAP_COLISUM equ $52
def MAP_MAZEWOD equ $53
def MAP_SLDFLR1 equ $54
def MAP_SLDFLR2 equ $55 ;sliding floor puzzles
def MAP_SLDFLR3 equ $56
def MAP_MAZE1 equ $57
def MAP_MAZE2 equ $58
def MAP_MAZE3 equ $59
def MAP_MMCRM1 equ $5a
def MAP_MMCRM2 equ $5b
def MAP_MMCRM3 equ $5c
def MAP_BTLDEMO equ $5d
def MAP_CSLBG equ $5e
;def unnamed equ $5f ;broken version of gateworld shop
