def CASTLE equ $00
def VILLAGE equ $01
def BAZAAR equ $02
def TRVGATE equ $03
def FARM equ $04
def SHPRD equ $05
def BATTLE1 equ $06
def BATTLE2 equ $07
def NEST equ $08
def STRDNGN equ $09
def WTMEDAL equ $0a ;king's secret path
;def unnamed equ $0b ;Castle treasure room
def  EGCNSLT equ $0c ;egg consultant
def PRDPRNT equ $0d
;def unnamed equ $0e ; Castle treasure room
def CHKSTND equ $0f ;bank
def CUTYGRL equ $10
;def unnamed equ $11
def LIBRARY equ $12
def STACK equ $13 ;Library back room
;def unnamed equ $14
;def unnamed equ $15
def MEDALMA equ $16
;def unnamed equ $17 ;corrupted version of copycat's room
def IN_WELL equ $18
def MDYHAND equ $19
def SPONSER equ $1a
def STABLEL equ $1b ;kingslime
def STABLER equ $1c ;coffin room
def SCHOOL equ $1d
def BAR equ $1e
def QUEEEN equ $1f
;def unnamed equ $20
;def unnamed equ $21
;def unnamed equ $22
def CHMBROP equ $23 ;first gate room
def CHMBR_G equ $24
def CHMBR_F equ $25
def CHMBR_E equ $26
def CHMBR_D equ $27
def CHMBR_C equ $28
def CHMBR_B equ $29
def CHMBR_A equ $2a
def CHMBR_S equ $2b
def CHMBR_1 equ $2c
def CHMBR_2 equ $2d
def CHMBR_3 equ $2e
def TERRYS equ $2f
def OLDWELL equ $30 ;Hale's boss room
def S_CAVE equ $31 ;heavy princess's room
def MELKID equ $32 ;Golm's boss room
def NEST_2 equ $33 ;Just named NEST. MadCat's boss room.
def ILMWOOD equ $34
def TOMDOLA equ $35
def CASINO equ $36
def GODTWR equ $37
def LONDARG equ $38
def RENUL equ $39
def ARPTWR equ $3a
def DANCER equ $3b
def T_CAVE equ $3c
def SPRING equ $3d
def HAPPY equ $3e
def LIFECOD equ $3f
def TRIAL1 equ $40
def TRIAL2 equ $41
def M_CAVE equ $42
def PRISON equ $43
def Z_CAVE equ $44
def HELCLD equ $45
def DRGCSTL equ $46
def HRGNCSL equ $47
def BRMSCSL equ $48
def ZOMACSL equ $49
def MT_TOP equ $4a
def ATTOM equ $4b
def EVIL_MT equ $4c
def MUDOCSL equ $4d
def BTWECSL equ $4e
def SCRTMAP equ $4f
def ITEMSP equ $50
def CHURCH equ $51
def COLISUM equ $52
def MAZEWOD equ $53
def SLDFLR1 equ $54
def SLDFLR2 equ $55 ;sliding floor puzzles
def SLDFLR3 equ $56
def MAZE1 equ $57
def MAZE2 equ $58
def MAZE3 equ $59
def MMCRM1 equ $5a
def MMCRM2 equ $5b
def MMCRM3 equ $5c
def BTLDEMO equ $5d
def CSLBG equ $5e
;def unnamed equ $5f ;broken version of gateworld shop
